// <auto-generated />
namespace TinyERP.Course.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Changing_TableName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changing_TableName));
        
        string IMigrationMetadata.Id
        {
            get { return "202007211310016_Changing_TableName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
