// <auto-generated />
namespace TinyERP.Course.Query.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_DenormalizedId_For_CourseDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_DenormalizedId_For_CourseDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202008201354488_Add_DenormalizedId_For_CourseDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
